name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.23', '1.22', '1.21' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@dc2a3036923c8e2613c6b9f87d16552646116273
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
