name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.23', '1.22', '1.21' ]
    uses: bytemare/workflows/.github/workflows/test-go.yml@71480f021da3783374aa9ba921199a2753fd7539
    with:
      command: cd .github && make test
      version: ${{ matrix.go }}
